// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/picture.proto

package picturepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MaxImages     int32                  `protobuf:"varint,2,opt,name=max_images,json=maxImages,proto3" json:"max_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_picture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateRequest) GetMaxImages() int32 {
	if x != nil {
		return x.MaxImages
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_picture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GenerateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_picture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`      // pending, processing, completed, failed
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"` // процент выполнения
	Images        []*ImageResult         `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_picture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StatusResponse) GetImages() []*ImageResult {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneIndex    int32                  `protobuf:"varint,1,opt,name=scene_index,json=sceneIndex,proto3" json:"scene_index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResult) Reset() {
	*x = ImageResult{}
	mi := &file_proto_picture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResult) ProtoMessage() {}

func (x *ImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResult.ProtoReflect.Descriptor instead.
func (*ImageResult) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{4}
}

func (x *ImageResult) GetSceneIndex() int32 {
	if x != nil {
		return x.SceneIndex
	}
	return 0
}

func (x *ImageResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ImageResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type RegenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SceneIndex    int32                  `protobuf:"varint,2,opt,name=scene_index,json=sceneIndex,proto3" json:"scene_index,omitempty"`
	CustomPrompt  string                 `protobuf:"bytes,3,opt,name=custom_prompt,json=customPrompt,proto3" json:"custom_prompt,omitempty"` // опционально
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRequest) Reset() {
	*x = RegenerateRequest{}
	mi := &file_proto_picture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRequest) ProtoMessage() {}

func (x *RegenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRequest.ProtoReflect.Descriptor instead.
func (*RegenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{5}
}

func (x *RegenerateRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RegenerateRequest) GetSceneIndex() int32 {
	if x != nil {
		return x.SceneIndex
	}
	return 0
}

func (x *RegenerateRequest) GetCustomPrompt() string {
	if x != nil {
		return x.CustomPrompt
	}
	return ""
}

type RegenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateResponse) Reset() {
	*x = RegenerateResponse{}
	mi := &file_proto_picture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateResponse) ProtoMessage() {}

func (x *RegenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_picture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateResponse.ProtoReflect.Descriptor instead.
func (*RegenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_picture_proto_rawDescGZIP(), []int{6}
}

func (x *RegenerateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegenerateResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RegenerateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_picture_proto protoreflect.FileDescriptor

const file_proto_picture_proto_rawDesc = "" +
	"\n" +
	"\x13proto/picture.proto\x12\tpicturepb\"D\n" +
	"\x0fGenerateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"max_images\x18\x02 \x01(\x05R\tmaxImages\"_\n" +
	"\x10GenerateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc1\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12.\n" +
	"\x06images\x18\x05 \x03(\v2\x16.picturepb.ImageResultR\x06images\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"_\n" +
	"\vImageResult\x12\x1f\n" +
	"\vscene_index\x18\x01 \x01(\x05R\n" +
	"sceneIndex\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"r\n" +
	"\x11RegenerateRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vscene_index\x18\x02 \x01(\x05R\n" +
	"sceneIndex\x12#\n" +
	"\rcustom_prompt\x18\x03 \x01(\tR\fcustomPrompt\"e\n" +
	"\x12RegenerateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf8\x01\n" +
	"\x0ePictureService\x12P\n" +
	"\x15GenerateIllustrations\x12\x1a.picturepb.GenerateRequest\x1a\x1b.picturepb.GenerateResponse\x12D\n" +
	"\rGetTaskStatus\x12\x18.picturepb.StatusRequest\x1a\x19.picturepb.StatusResponse\x12N\n" +
	"\x0fRegenerateImage\x12\x1c.picturepb.RegenerateRequest\x1a\x1d.picturepb.RegenerateResponseB\x17Z\x15./picturepb;picturepbb\x06proto3"

var (
	file_proto_picture_proto_rawDescOnce sync.Once
	file_proto_picture_proto_rawDescData []byte
)

func file_proto_picture_proto_rawDescGZIP() []byte {
	file_proto_picture_proto_rawDescOnce.Do(func() {
		file_proto_picture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_picture_proto_rawDesc), len(file_proto_picture_proto_rawDesc)))
	})
	return file_proto_picture_proto_rawDescData
}

var file_proto_picture_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_picture_proto_goTypes = []any{
	(*GenerateRequest)(nil),    // 0: picturepb.GenerateRequest
	(*GenerateResponse)(nil),   // 1: picturepb.GenerateResponse
	(*StatusRequest)(nil),      // 2: picturepb.StatusRequest
	(*StatusResponse)(nil),     // 3: picturepb.StatusResponse
	(*ImageResult)(nil),        // 4: picturepb.ImageResult
	(*RegenerateRequest)(nil),  // 5: picturepb.RegenerateRequest
	(*RegenerateResponse)(nil), // 6: picturepb.RegenerateResponse
}
var file_proto_picture_proto_depIdxs = []int32{
	4, // 0: picturepb.StatusResponse.images:type_name -> picturepb.ImageResult
	0, // 1: picturepb.PictureService.GenerateIllustrations:input_type -> picturepb.GenerateRequest
	2, // 2: picturepb.PictureService.GetTaskStatus:input_type -> picturepb.StatusRequest
	5, // 3: picturepb.PictureService.RegenerateImage:input_type -> picturepb.RegenerateRequest
	1, // 4: picturepb.PictureService.GenerateIllustrations:output_type -> picturepb.GenerateResponse
	3, // 5: picturepb.PictureService.GetTaskStatus:output_type -> picturepb.StatusResponse
	6, // 6: picturepb.PictureService.RegenerateImage:output_type -> picturepb.RegenerateResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_picture_proto_init() }
func file_proto_picture_proto_init() {
	if File_proto_picture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_picture_proto_rawDesc), len(file_proto_picture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_picture_proto_goTypes,
		DependencyIndexes: file_proto_picture_proto_depIdxs,
		MessageInfos:      file_proto_picture_proto_msgTypes,
	}.Build()
	File_proto_picture_proto = out.File
	file_proto_picture_proto_goTypes = nil
	file_proto_picture_proto_depIdxs = nil
}
